image: Ubuntu2004  # образ для сборки

stack: jdk 11  # версия JDK

branches:
  only:
    - master  # ветка git

build: off  # будем использовать свой скрипт сборки

install:
  - chmod +x gradlew
  - ls -la artifacts/  # проверяем что jar файл существует

before_test:
  # Диагностика перед запуском
  - echo "=== ДИАГНОСТИКА ==="
  - pwd
  - ls -la
  - echo "Jar file:"
  - ls -la artifacts/
  - echo "Java version:"
  - java -version
  - echo "=== ЗАПУСК СЕРВЕРА ==="

  # Запускаем сервер с выводом логов в файл
  - java -jar artifacts/app-ibank.jar -P:profile=test > server.log 2>&1 &
  - sleep 15  # увеличиваем время ожидания

  # Проверяем процессы
  - echo "=== ПРОВЕРКА ПРОЦЕССОВ ==="
  - ps aux | grep java || echo "Java процессов нет"
  - echo "=== ПРОВЕРКА ПОРТОВ ==="
  - netstat -tulpn | grep :99 || echo "Порт 9999 не занят"
  - echo "=== ПРОВЕРКА СЕРВЕРА ==="
  - curl -v http://localhost:9999 || wget -q --spider http://localhost:9999 || echo "Сервер не отвечает"
  - echo "=== ЛОГИ СЕРВЕРА ==="
  - cat server.log || echo "Логи недоступны"

test_script:
  - echo "=== ЗАПУСК ТЕСТОВ ==="
  - ./gradlew test -Dselenide.headless=true --info