image: Ubuntu2004  # образ для сборки

stack: jdk 11  # версия JDK

branches:
  only:
    - master  # ветка git

build: off  # будем использовать свой скрипт сборки

install:
  - chmod +x gradlew  # ДОЛЖНО БЫТЬ ПЕРВОЙ КОМАНДОЙ

before_test:
  # Запускаем сервер в фоновом режиме
  - java -jar artifacts/app-ibank.jar -P:profile=test &
  - sleep 10  # ждем запуска сервера
  - curl -f http://localhost:9999 || exit 1  # проверяем что сервер запустился

test_script:
  # Запускаем тесты в headless режиме
  - ./gradlew test -Dselenide.headless=true --info